import type { INodeProperties } from 'n8n-workflow';

export const catalogCreateProductFields: INodeProperties[] = [
	{
		displayName: 'Catalog ID',
		name: 'catalogId',
		type: 'string',
		required: true,
		default: '',
		description: 'ID of the catalog to add the product to, as returned by Get Many or Create',
		displayOptions: { show: { resource: ['catalog'], operation: ['createProduct'] } },
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		description: 'Name of the product',
		displayOptions: { show: { resource: ['catalog'], operation: ['createProduct'] } },
		routing: { send: { type: 'body', property: 'name' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['catalog'], operation: ['createProduct'] } },
		options: [
			{
				displayName: 'Additional Image URLs',
				name: 'additionalImageUrls',
				type: 'string',
				typeOptions: { multipleValues: true, multipleValueButtonText: 'Add Image URL' },
				default: [],
				description: 'Public URLs of extra product images',
				routing: { send: { type: 'body', property: 'additional_image_urls' } },
			},
			{
				displayName: 'Availability',
				name: 'availability',
				type: 'string',
				default: '',
				description: 'Availability status of the product, e.g. in stock or out of stock',
				routing: { send: { type: 'body', property: 'availability' } },
			},
			{
				displayName: 'Brand',
				name: 'brand',
				type: 'string',
				default: '',
				description: 'Brand name of the product',
				routing: { send: { type: 'body', property: 'brand' } },
			},
			{
				displayName: 'Category',
				name: 'category',
				type: 'string',
				default: '',
				description: 'Category the product belongs to',
				routing: { send: { type: 'body', property: 'category' } },
			},
			{
				displayName: 'Color',
				name: 'color',
				// Zaple's commerce catalog expects a free-text color name (e.g. "Red"),
				// not a hex value — n8n's 'color' type would send a hex swatch instead.
				// eslint-disable-next-line n8n-nodes-base/node-param-color-type-unused
				type: 'string',
				default: '',
				description: 'Color of the product',
				routing: { send: { type: 'body', property: 'color' } },
			},
			{
				displayName: 'Condition',
				name: 'condition',
				type: 'string',
				default: '',
				description: 'Condition of the product, e.g. new, refurbished, or used',
				routing: { send: { type: 'body', property: 'condition' } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'string',
				default: '',
				placeholder: 'e.g. INR',
				description: 'ISO 4217 currency code for the price, e.g. INR or USD',
				routing: { send: { type: 'body', property: 'currency' } },
			},
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				description: 'Description text of the product',
				routing: { send: { type: 'body', property: 'description' } },
			},
			{
				displayName: 'Gender',
				name: 'gender',
				type: 'string',
				default: '',
				description: 'Target gender of the product, e.g. male, female, or unisex',
				routing: { send: { type: 'body', property: 'gender' } },
			},
			{
				displayName: 'Image URL',
				name: 'imageUrl',
				type: 'string',
				default: '',
				description: 'Public URL of the main product image',
				routing: { send: { type: 'body', property: 'image_url' } },
			},
			{
				displayName: 'Inventory',
				name: 'inventory',
				type: 'number',
				default: 0,
				description: 'Available stock quantity of the product',
				routing: { send: { type: 'body', property: 'inventory' } },
			},
			{
				displayName: 'Material',
				name: 'material',
				type: 'string',
				default: '',
				description: 'Material the product is made of, e.g. cotton',
				routing: { send: { type: 'body', property: 'material' } },
			},
			{
				displayName: 'Origin Country',
				name: 'originCountry',
				type: 'string',
				default: '',
				placeholder: 'e.g. IN',
				description: 'Country of origin of the product',
				routing: { send: { type: 'body', property: 'origin_country' } },
			},
			{
				displayName: 'Pattern',
				name: 'pattern',
				type: 'string',
				default: '',
				description: 'Pattern of the product, e.g. striped',
				routing: { send: { type: 'body', property: 'pattern' } },
			},
			{
				displayName: 'Price',
				name: 'price',
				type: 'string',
				default: '',
				placeholder: 'e.g. 199.00',
				description: 'Price of the product',
				routing: { send: { type: 'body', property: 'price' } },
			},
			{
				displayName: 'Product Type',
				name: 'productType',
				type: 'string',
				default: '',
				description: 'Retailer-defined product type or category path',
				routing: { send: { type: 'body', property: 'product_type' } },
			},
			{
				displayName: 'Retailer ID',
				name: 'retailerId',
				type: 'string',
				default: '',
				description: 'Your unique identifier (SKU) for the product',
				routing: { send: { type: 'body', property: 'retailer_id' } },
			},
			{
				displayName: 'Sale Price',
				name: 'salePrice',
				type: 'string',
				default: '',
				description: 'Discounted sale price of the product',
				routing: { send: { type: 'body', property: 'sale_price' } },
			},
			{
				displayName: 'Sale Price End Date',
				name: 'salePriceEndDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-08-31',
				description: 'End of the sale price period',
				routing: { send: { type: 'body', property: 'sale_price_end_date' } },
			},
			{
				displayName: 'Sale Price Start Date',
				name: 'salePriceStartDate',
				type: 'string',
				default: '',
				placeholder: 'e.g. 2026-08-01',
				description: 'Start of the sale price period',
				routing: { send: { type: 'body', property: 'sale_price_start_date' } },
			},
			{
				displayName: 'Size',
				name: 'size',
				type: 'string',
				default: '',
				description: 'Size of the product, e.g. M or XL',
				routing: { send: { type: 'body', property: 'size' } },
			},
			{
				displayName: 'URL',
				name: 'url',
				type: 'string',
				default: '',
				description: 'Link to the product page on your website',
				routing: { send: { type: 'body', property: 'url' } },
			},
			{
				displayName: 'Visibility',
				name: 'visibility',
				type: 'string',
				default: '',
				description: 'Visibility of the product in the catalog, e.g. published or hidden',
				routing: { send: { type: 'body', property: 'visibility' } },
			},
		],
	},
];
