import type { INodeProperties } from 'n8n-workflow';

export const messageSendTemplateFields: INodeProperties[] = [
	{
		displayName: 'Template ID',
		name: 'templateId',
		type: 'string',
		required: true,
		default: '',
		description:
			'Send-API template identifier, as shown in the Zaple template library — NOT the numeric database ID',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
		routing: { send: { type: 'body', property: 'template_id' } },
	},
	{
		displayName: 'Country Code',
		name: 'countryCode',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'e.g. 91',
		description: 'Recipient country calling code without the + sign, e.g. 91 for India',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
		routing: { send: { type: 'body', property: 'country_code' } },
	},
	{
		displayName: 'Send To',
		name: 'sendTo',
		type: 'string',
		required: true,
		default: '',
		description: 'Recipient phone number without the country code',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
		routing: { send: { type: 'body', property: 'send_to' } },
	},
	{
		displayName: 'Template Arguments',
		name: 'templateArguments',
		type: 'string',
		typeOptions: { multipleValues: true, multipleValueButtonText: 'Add Argument' },
		default: [],
		description: 'Values for {{1}}, {{2}}, … in order — sent as template_argument1..N',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
	},
	{
		displayName: 'Quick Reply Payloads',
		name: 'quickReplyPayloads',
		type: 'string',
		typeOptions: { multipleValues: true, multipleValueButtonText: 'Add Payload' },
		default: [],
		description:
			'Payload values for the quick-reply buttons in button order — sent as quick_reply_payload1..N',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
	},
	{
		displayName: 'Media URL Type',
		name: 'mediaUrlType',
		type: 'options',
		options: [
			{ name: 'Base64', value: 'base64' },
			{ name: 'None', value: 'none' },
			{ name: 'Public URL', value: 'public_url' },
		],
		default: 'none',
		description: 'How the media for the template header is provided',
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
	},
	{
		displayName: 'Media URL',
		name: 'mediaUrl',
		type: 'string',
		default: '',
		description: 'Publicly accessible URL of the media file',
		displayOptions: {
			show: { resource: ['message'], operation: ['sendTemplate'], mediaUrlType: ['public_url'] },
		},
	},
	{
		displayName: 'Base64 Data',
		name: 'base64Data',
		type: 'string',
		default: '',
		description:
			'Base64-encoded content of the media file, e.g. {{ $binary.data.data }} from a previous node',
		displayOptions: {
			show: { resource: ['message'], operation: ['sendTemplate'], mediaUrlType: ['base64'] },
		},
	},
	{
		displayName: 'File Name',
		name: 'fileName',
		type: 'string',
		default: '',
		description: 'File name shown to the recipient — used for document media',
		displayOptions: {
			show: {
				resource: ['message'],
				operation: ['sendTemplate'],
				mediaUrlType: ['base64', 'public_url'],
			},
		},
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['message'], operation: ['sendTemplate'] } },
		options: [
			{
				displayName: 'Biz Opaque Callback Data',
				name: 'bizOpaqueCallbackData',
				type: 'string',
				default: '',
				description: 'Stringified JSON echoed back in status webhooks',
				routing: { send: { type: 'body', property: 'biz_opaque_callback_data' } },
			},
			{
				displayName: 'Header Argument',
				name: 'headerArgument',
				type: 'string',
				default: '',
				description: 'Dynamic text value for the template header',
				routing: { send: { type: 'body', property: 'header_argument' } },
			},
			{
				displayName: 'Tags',
				name: 'tags',
				type: 'string',
				typeOptions: { multipleValues: true, multipleValueButtonText: 'Add Tag' },
				default: [],
				description: 'Tags attached to the message for filtering and reporting',
				routing: { send: { type: 'body', property: 'tags' } },
			},
		],
	},
];
