import type { INodeProperties } from 'n8n-workflow';

export const templateCreateFields: INodeProperties[] = [
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		required: true,
		default: '',
		description: 'Template title (max 255 characters)',
		displayOptions: { show: { resource: ['template'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'title' } },
	},
	{
		displayName: 'Category',
		name: 'category',
		type: 'options',
		required: true,
		options: [
			{
				name: 'Authentication',
				value: 'authentication',
				description: 'One-time passcodes and identity verification messages',
			},
			{
				name: 'Marketing',
				value: 'marketing',
				description: 'Promotions, offers, and announcements',
			},
			{
				name: 'Utility',
				value: 'utility',
				description: 'Transactional updates about an existing order or account',
			},
			{
				name: 'Utility Marketing',
				value: 'utility_marketing',
				description: 'Utility template that also includes marketing content',
			},
		],
		default: 'utility',
		description: 'WhatsApp template category',
		displayOptions: { show: { resource: ['template'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'category' } },
	},
	{
		displayName: 'Language',
		name: 'language',
		type: 'string',
		required: true,
		default: 'en_US',
		description: 'Template language code, for example en_US',
		displayOptions: { show: { resource: ['template'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'language' } },
	},
	{
		displayName: 'Content',
		name: 'content',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		description:
			'Body text; use {{1}}, {{2}} or named variables. Not required for authentication templates.',
		displayOptions: { show: { resource: ['template'], operation: ['create'] } },
		routing: { send: { type: 'body', property: 'content' } },
	},
	{
		displayName: 'Buttons (JSON)',
		name: 'buttonsJson',
		type: 'json',
		default: '',
		// Example JSON must show the API's lowercase 'url' type/key verbatim.
		// eslint-disable-next-line n8n-nodes-base/node-param-description-miscased-url
		description:
			'JSON array of buttons, for example: [{"type":"quick_reply","replies":[{"text":"Yes"}]},{"type":"url","websites":[{"text":"Visit","url":"https://example.com"}]}]',
		displayOptions: { show: { resource: ['template'], operation: ['create'] } },
	},
	{
		displayName: 'Template Location (JSON)',
		name: 'templateLocationJson',
		type: 'json',
		default: '',
		description:
			'JSON object for a location header, for example: {"name":"Head Office","address":"123 Main St","latitude":"22.30","longitude":"70.80"}',
		displayOptions: { show: { resource: ['template'], operation: ['create'] } },
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['template'], operation: ['create'] } },
		options: [
			{
				displayName: 'Add Security Recommendation',
				name: 'addSecurityRecommendation',
				type: 'boolean',
				default: false,
				description:
					'Whether to add the security recommendation line (authentication templates only)',
				routing: { send: { type: 'body', property: 'addSecurityRecommendation' } },
			},
			{
				displayName: 'Code Expiration Minutes',
				name: 'codeExpirationMinutes',
				type: 'number',
				default: 10,
				description: 'Minutes until the one-time code expires (authentication templates only)',
				routing: { send: { type: 'body', property: 'codeExpirationMinutes' } },
			},
			{
				displayName: 'Content Type',
				name: 'contentType',
				type: 'options',
				options: [
					{ name: 'Document', value: 'document' },
					{ name: 'Image', value: 'image' },
					{ name: 'Location', value: 'location' },
					{ name: 'None', value: 'none' },
					{ name: 'Text', value: 'text' },
					{ name: 'Video', value: 'video' },
				],
				default: 'none',
				description: 'Type of the template header',
				routing: { send: { type: 'body', property: 'contentType' } },
			},
			{
				displayName: 'Copy OTP Button Text',
				name: 'copyOtpButtonText',
				type: 'string',
				default: '',
				description: 'Label of the copy-code button (authentication templates only)',
				routing: { send: { type: 'body', property: 'copyOtpButtonText' } },
			},
			{
				displayName: 'Enable Code Expiration',
				name: 'enableCodeExpiration',
				type: 'boolean',
				default: false,
				description: 'Whether the one-time code expires (authentication templates only)',
				routing: { send: { type: 'body', property: 'enableCodeExpiration' } },
			},
			{
				displayName: 'Footer Text',
				name: 'footerText',
				type: 'string',
				default: '',
				description: 'Footer text shown below the template body',
				routing: { send: { type: 'body', property: 'footerText' } },
			},
			{
				displayName: 'Header Text',
				name: 'headerText',
				type: 'string',
				default: '',
				description: 'Header text (max 60 characters); used when Content Type is Text',
				routing: { send: { type: 'body', property: 'headerText' } },
			},
			{
				displayName: 'Template Document',
				name: 'templateDocument',
				type: 'string',
				default: '',
				description: 'PDF URL for the document header',
				routing: { send: { type: 'body', property: 'templateDocument' } },
			},
			{
				displayName: 'Template Image',
				name: 'templateImage',
				type: 'string',
				default: '',
				description: 'Public URL or base64 data URI of the header image',
				routing: { send: { type: 'body', property: 'templateImage' } },
			},
			{
				displayName: 'Template Video',
				name: 'templateVideo',
				type: 'string',
				default: '',
				description: 'Public URL or base64 data URI of the header video',
				routing: { send: { type: 'body', property: 'templateVideo' } },
			},
			{
				displayName: 'Variable Samples',
				name: 'variableSamples',
				type: 'string',
				typeOptions: { multipleValues: true, multipleValueButtonText: 'Add Sample' },
				default: [],
				description: 'Example values for the template variables, in order (used by Meta review)',
				routing: { send: { type: 'body', property: 'variable_samples' } },
			},
			{
				displayName: 'Variable Type',
				name: 'variableType',
				type: 'options',
				options: [
					{ name: 'Named', value: 'named' },
					{ name: 'Numeric', value: 'numeric' },
				],
				default: 'numeric',
				description: 'Style of body variables: numbered ({{1}}) or named ({{name}})',
				routing: { send: { type: 'body', property: 'variable_type' } },
			},
		],
	},
];
